-- Lab 3

-- Total not between 1 to 100

SELECT * FROM SALES WHERE TOTAL_AMOUNT NOT BETWEEN 1 and 100;

-- qunatity has value 20/2/10
SELECT * FROM SALES WHERE QUANTITY IN(20,2,10);

-- product name starts with MOB

SELECT * FROM PRODUCT WHERE PRODUCT_NAME LIKE 'MOB%';

SELECT * FROM PRODUCT WHERE PRODUCT_NAME LIKE 'Mob%';

-- TOTAL AMOUNT > 50,100 & 200

SELECT * FROM SALES WHERE TOTAL_AMOUNT > ANY(50,100,200);

-- product color null

SELECT * FROM PRODUCT WHERE COLOR IS NULL;

-- Total > 100 & quantity <20;

SELECT * FROM SALES WHERE TOTAL_AMOUNT>100 and QUANTITY<20;

