--FOR LOOP
DECLARE 
  COUNTER NUMBER(2):=10;
  
BEGIN
  FOR COUNTER  IN 10..20 
    LOOP
      DBMS_OUTPUT.PUT_LINE('COUNTER - '||COUNTER);
    END LOOP;
  END;

--FOR LOOP REVERSE
DECLARE 
  COUNTER NUMBER(2):=10;
  
BEGIN
  FOR COUNTER  IN  REVERSE  20..10 
    LOOP
      DBMS_OUTPUT.PUT_LINE('COUNTER - '||COUNTER);
    END LOOP;
  END;