--WHILE
DECLARE 
  COUNTER NUMBER(2) := 10;
BEGIN
  WHILE COUNTER <20
 
LOOP
  DBMS_OUTPUT.PUT_LINE('COUNTER '||COUNTER);
  COUNTER:=COUNTER + 1;
  
  END LOOP;
END;

-- WHILE STATEMENT INCREMENT BY 2
DECLARE 
  COUNTER NUMBER(2) := 10;
BEGIN
  WHILE COUNTER <20
 
LOOP
  DBMS_OUTPUT.PUT_LINE('COUNTER '||COUNTER);
  COUNTER:=COUNTER + 2;
  
  END LOOP;
END;
